# name: CI workflow

# on:
#   push:
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container: python:3.9-slim
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       - name: Lint with flake8
#         run: |
#           flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
#           flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
#       - name: Run unit tests with nose
#         run:
#           nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
name: CI workflow

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    # Cache dependencies to speed up workflow
    env:
      CACHE_DIR: ~/.cache/pip

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Restore cached dependencies
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Save dependencies cache for future runs
      - name: Save dependencies cache
        if: success()
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run:
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app